---
- name: Display the config
  debug:
    msg: "The hostname is {{ ansible_hostname }}, the OS is {{ ansible_system }}, Python version is {{ansible_python_version}}
          Master role: {{ ansible_parent_role_names[0]}}
          Calling role: {{ ansible_parent_role_names[0] | default(role_name) }}"

- name: Print all available facts
  ansible.builtin.debug:
    var: ansible_facts

- name: Display full facts
  debug:
    msg: "
          Memory: {{ansible_memory_mb}}
          Memory: {{ansible_memory_mb}}
          Mount: {{ansible_mounts}}
          pkg_mgr: {{ansible_pkg_mgr}}
          Memory: {{ansible_memory_mb}}"

- name: print json
  debug:
    msg: "{{jsondata}}"
  when: jsondata is defined
         
