- name: Gather the package facts
  ansible.builtin.package_facts:
    manager: auto

- name: Print the package facts
  ansible.builtin.debug:
    var: ansible_facts.packages

- name: Check whether a package called python is installed
  ansible.builtin.debug:
    msg: "{{ ansible_facts.packages['python'] | length }} versions of python are installed!"
  when: "'python' in ansible_facts.packages"