---
# might not work when dealing with remote host, need testing
- name: Create state_files directory
  file:
    path: /tmp/state_files
    state: directory
- name: Create a state file
  vars: 
    state_file: {
      package: "python",
      version: "3.2.1",
      test: {
        tested: "hi"
      }
    }
  copy:
    dest: /tmp/state_files/my_file.json
    content: "{{ state_file| to_nice_yml }}"