---
# might not work when dealing with remote host, need testing
- name: Display the yaml file content
  shell: cat /ansible/state_files/{{current_package}}.json
  register: result

- name: save the yaml data to a Variable as a Fact
  ansible.builtin.set_fact:
    state_data: "{{ result.stdout | from_yaml }}"

- name: display yaml content
  debug:
    msg: "{{ state_data }}"
