
- name: Get content of remote file
  ansible.builtin.slurp:
    src: ../groups/{{group_name}}.yml
  register: remote_file

- name: Interpret remote file content as yaml
  ansible.builtin.set_fact:
    desired: '{{ remote_file.content | b64decode | from_yaml }}'

# - name: print loaded variable 
#   ansible.builtin.debug:
#     msg: "key: {{ item.key }} ;; value {{ item.value }}"
#   loop: "{{ group_configuration | dict2items }}"

# - name: Load group_configuration into facts
#   ansible.builtin.set_fact:
#     "{{item.key}}_configuration": "{{item.value}}"
#   loop: "{{ group_configuration | dict2items }}"
