---
# might not work when dealing with remote host, need testing
- name: Display the yaml file content
  shell: cat /ansible/installed_state_file.yaml
  register: result

- name: save the yaml data to a Variable as a Fact
  ansible.builtin.set_fact:
    installed_state: "{{ result.stdout | from_yaml }}"

