--- 
# check desired

# check current

- name: print config
  debug:
    msg: "{{desired}}"

# compare 
- name: compared python version
  debug:
    msg: "current_version : is higher than desired"
  var:
    current_version: "{{current['python']['version']}}"
    desired_version: "{{desired['python']['version']}}"
  when: current_version is version(desired_version, '>=')

