--- 

# check desired

# check current

- name: print config
  debug:
    msg: "{{desired}}"

- name: set default
  ansible.builtin.set_facts:
    desired:
      python:
        version: "3.12.11"
  when: desired["python"] is undefined

- name: set var
  ansible.builtin.template:
    current_version: "{{current['python']['version']}}"
    desired_version: "{{desired['python']['version']}}"

# compare 
- name: compared python version
  debug:
    msg: "current_version : is higher than desired"
  when: current_version is version(desired_version, '>=')

