--- 
# compare 
- name: compared python version
  debug:
    msg: "current version : {{installed_state.python.version}} is higher than desired : {{desired.python.version}}"
  when: installed_state.python.version is version(desired.python.version, '>=')

