--- 
- name: get python version
  shell: python -V
  register: result.stdout| regex_replace('Python ', '')

#| regex_replace('Python ', ' ')
- name: create temp Variable
  ansible.builtin.set_fact:
    current_python: "{'python': {'version': '{{ result }}'}}"

- name: gather current facts
  ansible.builtin.set_fact:
    installed_state: "{{ installed_state | combine( current_python, recursive=true ) }}"
  