---
- hosts: all
  tasks:
  - name: Include visual_studio_2022
    include_role:
      name: visual_studio_2022

  - name: Include common
    include_role:
      name: common
  
  - name: Trigger specified roles
    include_role:
      name: "{{item}}"
    when: desired["{{item}}"] is defined
    loop:
    - visual_studio_2022
    - teamcity
    - ps4_sdk
    - ps5_sdk


  